name: Static checks

on: pull_request

jobs:
  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master
    permissions:
      security-events: write
      contents: read
  todos:
    uses: lidofinance/linters/.github/workflows/todos.yml@master
