name: Test wallets
on:
  pull_request:
  schedule:
    - cron:  '0 2,14 * * *'
jobs:
  test-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run lint
        run: yarn lint
      - name: Build Components
        run: yarn build

      - name: Install dependencies in wallets-testing
        working-directory: wallets-testing
        run: yarn install --immutable
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run wallets tests
        run: xvfb-run --auto-servernum -- yarn test
        working-directory: wallets-testing
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          WALLET_SECRET_PHRASE: ${{ secrets.WALLET_SECRET_PHRASE }}
          WALLET_PASSWORD: ${{ secrets.WALLET_PASSWORD }}
          NODE_OPTIONS: --max-old-space-size=4096
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: playwright-report
          path: wallets-testing/playwright-report/
          retention-days: 30

      - name: Discord notification
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: lidofinance/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{
            "title": "🙅‍♂️ Periodically running wallet tests failed",
            "description": "[🔗 Tests summary](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})",
            "color": 13959168
          }]'

      - name: Discord notification
        if: ${{ success() && github.event_name == 'schedule' }}
        uses: lidofinance/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{
            "title": "💆‍♂️️ Periodically running wallet tests pass",
            "description": "There is no link here, just relax",
            "color": 47872
          }]'
